apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-drc
  labels:
    app: dummy-drc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{- include "laa-dces-dummy-drc.selectorLabels" . | nindent 4 }} # this should match the selector in service.yml
  template:
    metadata:
      labels:
        app: {{- include "laa-dces-dummy-drc.selectorLabels" . | nindent 4 }} # this should match the selector in service.yml
    spec:
      containers:
        - name: dummy-drc
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 8080
            - containerPort: 8443