apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dummy-drc-ingress
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: dummy-drc-ingress-laa-dces-dummy-drc-dev-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
#    nginx.ingress.kubernetes.io/ssl-redirect: "true"
#    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
#    nginx.ingress.kubernetes.io/auth-tls-secret: "${NAMESPACE}/client-ca-secret"  # Assuming the secret with CA certs for mTLS is named 'ca-cert'
#    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
#    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
spec:
  ingressClassName: default
  tls:
    - hosts:
        - laa-dces-dummy-drc-dev.apps.live.cloud-platform.service.justice.gov.uk
  rules:
    - host: laa-dces-dummy-drc-dev.apps.live.cloud-platform.service.justice.gov.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dummy-drc-service # this should match the metadata.name in service.yml
                port:
                  number: 8080
